[build]
  command = "gatsby build"
  publish = "public"

[template]
  incoming-hooks = ["Ghost"]

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "netlify-plugin-minify-html"

  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]

  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = false
